# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x0cImageService\"$\n\x0cImageRequest\x12\x14\n\x0c\x62\x61se64_image\x18\x01 \x01(\t\"#\n\rImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32X\n\x0cImageService\x12H\n\x0bUploadImage\x12\x1a.ImageService.ImageRequest\x1a\x1b.ImageService.ImageResponse\"\x00\x42\x1fZ\x1dimgresizer/golang client/mainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035imgresizer/golang client/main'
  _globals['_IMAGEREQUEST']._serialized_start=28
  _globals['_IMAGEREQUEST']._serialized_end=64
  _globals['_IMAGERESPONSE']._serialized_start=66
  _globals['_IMAGERESPONSE']._serialized_end=101
  _globals['_IMAGESERVICE']._serialized_start=103
  _globals['_IMAGESERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
